version: '3.8'

services:
  faceit-stats:
    build: .
    container_name: faceit-stats-pro
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
